import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {


  return (
    <html lang="es">
      <body className="h-screen flex flex-col">

        <Navbar />

        <main className="flex-1 p-2">
        {children}
        </main>
        
        </body>
    </html>
  )
}
